title: Jingxuan Han's Homepage
page-top-title: Jingxuan Han
top-section-bg-text: Be what you wanna be
home-subtitle: Jingxuan Han&ensp;|&ensp;CV Researcher
copyright-text: '&copy; Jingxuan Han 2026. All Rights Reserved.'